export const resources = {
  'en-GB': {
    translation: {
      language: { label: 'Language', english: 'English', spanish: 'Español (LatAm)' },
      common: {
        petSeenHome: 'Pet Seen home',
        backToHome: 'Back to home',
        backToCases: 'All Pet Seen cases',
        nearbyPets: 'Nearby pets',
        signIn: 'Sign in', account: 'My account',
        continue: 'Continue',
        submitSighting: 'Submit sighting',
        goHome: 'Go home',
        dog: 'Dog', cat: 'Cat', young: 'Young', adult: 'Adult', senior: 'Senior',
      },
      home: {
        eyebrow: 'Helping pets get home', title: 'What happened?',
        intro: 'Start with the option that best fits. You can report a sighting without an account.',
        missingLabel: 'My pet is missing', missingDescription: 'Create a missing-pet case and share it with people nearby.',
        sightingLabel: 'I saw a pet', sightingDescription: 'A photo, place and time could help someone bring a pet home.',
        foundLabel: 'I found a pet', foundDescription: 'Tell the community about a pet that is safe with you.',
        howItWorks: 'How Pet Seen works', howItWorksTitle: 'Clear reports for people nearby.',
        essentialsTitle: 'Share the essentials.', essentialsBody: 'Add a photo, the last place the pet was seen and a helpful description.',
        privacyTitle: 'Keep exact locations private.', privacyBody: 'Public maps show a broader area, while the owner sees precise sighting details.',
        neighboursTitle: 'Give neighbours one route to help.', neighboursBody: 'Every public case has a simple sighting form.',
      },
      missingCase: {
        progress: 'Missing-pet case', step: 'Step {{current}} of {{total}}', eyebrow: 'Start a case', title: 'Tell us about your pet.',
        intro: 'We’ll help you create a shareable page. You can review everything before it goes public.', details: 'Pet details',
        petName: 'Pet’s name', species: 'Species', breed: 'Breed', breedHint: 'For example, border collie', markings: 'Colour or markings', markingsHint: 'For example, black with white chest', description: 'Helpful details', descriptionHint: 'Collar, temperament or anything that may help people recognise your pet.',
        photo: 'Photo', addPhoto: 'Add a clear photo', photoHint: 'JPG or PNG, up to 10 MB. We remove photo metadata before sharing.', invalidPhoto: 'Choose a JPG or PNG image no larger than 10 MB.', preparePhotoError: 'We could not prepare that photo. Try a different JPG or PNG image.', saving: 'Saving pet details…', saveError: 'We could not save your pet details. Please try again.', signInTitle: 'Sign in to start a case.', signInBody: 'Missing-pet cases are linked to an account so you can manage them safely.', savedTitle: 'Pet details saved.', savedBody: 'Your pet is ready for the next step: adding where they were last seen.',
        lastSeenQuestion: 'When and where was {{petName}} last seen?', lastSeen: 'Last seen', location: 'Location',
        exactLocationNote: 'This exact location is only visible to you and Pet Seen administrators.',
      },
      publicCase: {
        imageDescription: 'Illustration of {{petName}}, a black dog with a white chest', status: 'Missing', title: '{{petName}} is missing.',
        lead: 'A black-and-white dog missing from Victoria Park, Hackney.', leadForPet: '{{petName}} is missing. Please share a sighting if you can help.', lastSeen: 'Last seen', lastSeenValue: 'Today at around 4:30 pm', lastSeenUnknown: 'Time not provided',
        area: 'Area', areaValue: 'Victoria Park area', approximateArea: 'Approximate area', action: 'I saw {{petName}}', privacy: 'Your report can include the exact place. It is shared only with {{petName}}’s owner and Pet Seen administrators.',
        about: 'About {{petName}}', descriptionTitle: 'More information', description: '{{petName}} is a friendly medium-sized dog. He was wearing a faded red collar. Please do not chase him; report where and when you saw him instead.',
        mapNote: 'This map shows an approximate area to protect {{petName}}’s privacy.', mapLabel: 'Approximate location map for {{petName}}', loadingTitle: 'Loading this case', loadingBody: 'Please wait while we get the public case details.', notFoundTitle: 'This case is no longer available.', notFoundBody: 'It may have been closed or the link may be incorrect.', unavailableTitle: 'This public case is unavailable.', unavailableBody: 'Please try again shortly.',
      },
      contentReport: { trigger: 'Report this case', title: 'Report a problem with this case.', intro: 'Tell us what looks wrong. Your report is reviewed by Pet Seen staff.', reason: 'Reason', details: 'More detail (optional)', submit: 'Send report', sending: 'Sending…', error: 'We could not send your report. Please try again.', thanksTitle: 'Report received.', thanksBody: 'Thank you. Pet Seen staff will review it.', reasons: { incorrect: 'Incorrect or outdated information', harmful: 'Harmful or unsafe content', scam: 'Possible scam or impersonation', other: 'Something else' } },
      moderation: { eyebrow: 'Staff area', title: 'Content reports', intro: 'Review reports from public case pages and record the outcome.', checking: 'Checking staff access…', deniedTitle: 'This area is for Pet Seen staff.', deniedBody: 'Sign in with an authorised staff account to review content reports.', loading: 'Loading reports…', error: 'We could not load the moderation queue. Please try again.', emptyTitle: 'No reports need review.', emptyBody: 'New reports from public case pages will appear here.', unavailableCase: 'Unavailable case', viewCase: 'View public case', statusLabel: 'Report status', status: { open: 'Open', reviewed: 'Reviewed', dismissed: 'Dismissed', actioned: 'Actioned' } },
      dashboard: {
        eyebrow: 'Your cases', title: 'Manage your missing-pet cases.', intro: 'Keep the details current, then close the case when it no longer needs to be shared.', newCase: 'Start a new case', loading: 'Loading your cases…', loadError: 'We could not load your cases. Please try again.', signInTitle: 'Sign in to manage your cases.', signInBody: 'Your cases are linked to your account so only you can update them.', emptyTitle: 'You have no missing-pet cases yet.', emptyBody: 'Start a case when you need help from people nearby.', viewPublic: 'View public page', pet: 'Pet', caseTitle: 'Case title', petName: 'Pet’s name', breed: 'Breed', colour: 'Colour or markings', description: 'Helpful details', lastSeenPlace: 'Last seen place or landmark', lastSeenTime: 'Last seen time', locationNote: 'Exact locations are never shown publicly.', saveChanges: 'Save changes', saving: 'Saving…', saved: 'Your changes have been saved.', saveError: 'We could not save those changes. Please try again.', statusError: 'We could not update this case. Please try again.', statusSaved: 'Case status updated.', edit: 'Edit details', changeStatus: 'Case status', reunitedNote: 'Marked as reunited. This case is no longer public.', closedNote: 'This case is closed and no longer public.', cancel: 'Cancel', sightings: 'Sighting reports', sightingTimeline: 'Exact sighting locations', sightingPrivacy: 'These locations are private to you and Pet Seen staff.', coordinates: 'Exact map location', status: { draft: 'Draft', published: 'Still missing — public', closed: 'Closed — not public', reunited: 'Reunited — not public', removed: 'Removed', expired: 'Expired' },
      },
      sighting: {
        progress: 'Report a sighting', eyebrow: 'No account needed', title: 'Tell us what you saw.',
        intro: 'A clear report gives an owner useful information without sharing your contact details publicly.',
        petQuestion: 'Do you know which pet this might be?', petOrCase: 'Pet or case', knownPet: 'Milo — Victoria Park area', unknownPet: 'I’m not sure / a different pet', petHelp: 'You can submit a sighting even if you do not know the pet.',
        whenWhere: 'Where and when?', where: 'Where did you see the pet?', whereHint: 'Street, park or landmark', when: 'When did you see them?', whenHint: 'For example, today at 5:15 pm',
        detailsQuestion: 'What did you notice?', details: 'Details', detailsHint: 'Colour, collar, direction of travel or anything else that may help.',
        addPhoto: 'Add a photo', photoHint: 'Optional, but helpful if it is safe to take one.', privacy: 'Your exact location is shared only with the linked case owner and Pet Seen administrators.', locationHelp: 'Use your current location, move the pin, or enter coordinates manually.', useLocation: 'Use my location', pinNote: 'Move the pin or tap the map to confirm the exact place you saw the pet.', latitude: 'Latitude', longitude: 'Longitude', locationUnavailable: 'Your browser cannot provide a location. Move the pin or enter coordinates manually.', locationDenied: 'We could not access your location. Allow location access, then try again, or move the pin or enter coordinates manually.', invalidLocation: 'Enter a valid latitude and longitude.', unavailable: 'Sighting reports are unavailable in this environment.', submitting: 'Submitting…', thanksTitle: 'Sighting shared.', thanksBody: 'Thank you. If you linked a case, its owner can now see the exact place and time you reported.',
      },
      auth: {
        eyebrow: 'Account access', title: 'Sign in with your email.', accountTitle: 'Your account', intro: 'We’ll email you a secure link. No password is needed.', emailLabel: 'Email address', emailHint: 'you@example.com', sendLink: 'Email me a sign-in link', sentTitle: 'Check your email.', sentBody: 'We sent a secure sign-in link to {{email}}.', toast: 'You’re signed in.', privacy: 'We use your email only to secure your account and contact you about your cases.', setupNote: 'Authentication needs local environment settings before you can send a sign-in link.', notConfigured: 'Authentication is not configured in this environment.', loading: 'Checking your sign-in status…', signedInTitle: 'You’re signed in.', signedInBody: 'Your account is using {{email}}.', signOut: 'Sign out',
      },
      placeholders: {
        laterRelease: 'Later release', foundTitle: 'Found-pet reports are coming next.', foundBody: 'For now, please use a sighting report to share where you saw a pet.',
        accountAccess: 'Account access', authTitle: 'Sign in will use a secure email link.', authBody: 'You will not need a password. This is being built with the missing-pet case flow.',
        notFound: 'Not found', notFoundTitle: 'This page is not here yet.',
      },
      footer: 'Helping pets get home, together.',
    },
  },
  'es-419': {
    translation: {
      language: { label: 'Idioma', english: 'Inglés', spanish: 'Español (LatAm)' },
      common: {
        petSeenHome: 'Inicio de Pet Seen', backToHome: 'Volver al inicio', backToCases: 'Todos los casos de Pet Seen', nearbyPets: 'Mascotas cerca', signIn: 'Iniciar sesión', account: 'Mi cuenta', continue: 'Continuar', submitSighting: 'Enviar avistamiento', goHome: 'Ir al inicio', dog: 'Perro', cat: 'Gato', young: 'Joven', adult: 'Adulto', senior: 'Mayor',
      },
      home: {
        eyebrow: 'Ayudamos a que las mascotas vuelvan a casa', title: '¿Qué pasó?', intro: 'Elige la opción que mejor describa la situación. Puedes reportar un avistamiento sin crear una cuenta.',
        missingLabel: 'Mi mascota está perdida', missingDescription: 'Crea un caso de mascota perdida y compártelo con personas cerca.',
        sightingLabel: 'Vi una mascota', sightingDescription: 'Una foto, el lugar y la hora pueden ayudar a que una mascota vuelva a casa.',
        foundLabel: 'Encontré una mascota', foundDescription: 'Cuéntale a la comunidad que tienes a salvo una mascota.',
        howItWorks: 'Cómo funciona Pet Seen', howItWorksTitle: 'Reportes claros para las personas cerca.',
        essentialsTitle: 'Comparte lo esencial.', essentialsBody: 'Agrega una foto, el último lugar donde se vio a la mascota y una descripción útil.',
        privacyTitle: 'Mantén privados los lugares exactos.', privacyBody: 'Los mapas públicos muestran un área más amplia, mientras que la persona dueña ve los detalles precisos.',
        neighboursTitle: 'Dale a tus vecinos una forma de ayudar.', neighboursBody: 'Cada caso público tiene un formulario sencillo para reportar avistamientos.',
      },
      missingCase: {
        progress: 'Caso de mascota perdida', step: 'Paso {{current}} de {{total}}', eyebrow: 'Inicia un caso', title: 'Cuéntanos sobre tu mascota.', intro: 'Te ayudaremos a crear una página para compartir. Podrás revisar todo antes de que se publique.', details: 'Datos de la mascota',
        petName: 'Nombre de la mascota', species: 'Especie', breed: 'Raza', breedHint: 'Por ejemplo, border collie', markings: 'Color o marcas', markingsHint: 'Por ejemplo, negro con el pecho blanco', description: 'Detalles útiles', descriptionHint: 'Collar, temperamento o cualquier detalle que ayude a reconocer a tu mascota.',
        photo: 'Foto', addPhoto: 'Agrega una foto clara', photoHint: 'JPG o PNG, hasta 10 MB. Quitamos los metadatos antes de compartirla.', invalidPhoto: 'Elige una imagen JPG o PNG de hasta 10 MB.', preparePhotoError: 'No pudimos preparar esa foto. Prueba con otra imagen JPG o PNG.', saving: 'Guardando datos de la mascota…', saveError: 'No pudimos guardar los datos de tu mascota. Inténtalo de nuevo.', signInTitle: 'Inicia sesión para comenzar un caso.', signInBody: 'Los casos de mascotas perdidas están vinculados a una cuenta para que puedas gestionarlos de forma segura.', savedTitle: 'Datos de la mascota guardados.', savedBody: 'Tu mascota está lista para el siguiente paso: agregar dónde se vio por última vez.', lastSeenQuestion: '¿Cuándo y dónde se vio por última vez a {{petName}}?', lastSeen: 'Última vez visto', location: 'Lugar', exactLocationNote: 'Este lugar exacto solo será visible para ti y las personas administradoras de Pet Seen.',
      },
      publicCase: {
        imageDescription: 'Ilustración de {{petName}}, un perro negro con el pecho blanco', status: 'Perdido', title: '{{petName}} está perdido.', lead: 'Un perro blanco y negro perdido en Victoria Park, Hackney.', leadForPet: '{{petName}} está perdido/a. Comparte un avistamiento si puedes ayudar.', lastSeen: 'Última vez visto', lastSeenValue: 'Hoy alrededor de las 4:30 p. m.', lastSeenUnknown: 'No se indicó la hora', area: 'Área', areaValue: 'Zona de Victoria Park', approximateArea: 'Área aproximada', action: 'Vi a {{petName}}', privacy: 'Tu reporte puede incluir el lugar exacto. Solo se comparte con la persona dueña de {{petName}} y las personas administradoras de Pet Seen.', about: 'Sobre {{petName}}', descriptionTitle: 'Más información', description: '{{petName}} es un perro mediano y amigable. Llevaba un collar rojo desgastado. Por favor, no lo persigas; mejor reporta dónde y cuándo lo viste.', mapNote: 'Este mapa muestra un área aproximada para proteger la privacidad de {{petName}}.', mapLabel: 'Mapa de ubicación aproximada de {{petName}}', loadingTitle: 'Cargando este caso', loadingBody: 'Espera mientras obtenemos los datos públicos del caso.', notFoundTitle: 'Este caso ya no está disponible.', notFoundBody: 'Puede que se haya cerrado o que el enlace sea incorrecto.', unavailableTitle: 'Este caso público no está disponible.', unavailableBody: 'Inténtalo de nuevo en unos momentos.',
      },
      contentReport: { trigger: 'Reportar este caso', title: 'Reporta un problema con este caso.', intro: 'Cuéntanos qué parece incorrecto. El equipo de Pet Seen revisará tu reporte.', reason: 'Motivo', details: 'Más detalles (opcional)', submit: 'Enviar reporte', sending: 'Enviando…', error: 'No pudimos enviar tu reporte. Inténtalo de nuevo.', thanksTitle: 'Reporte recibido.', thanksBody: 'Gracias. El equipo de Pet Seen lo revisará.', reasons: { incorrect: 'Información incorrecta o desactualizada', harmful: 'Contenido dañino o inseguro', scam: 'Posible estafa o suplantación', other: 'Otro motivo' } },
      moderation: { eyebrow: 'Área del equipo', title: 'Reportes de contenido', intro: 'Revisa los reportes de las páginas públicas y registra el resultado.', checking: 'Comprobando acceso del equipo…', deniedTitle: 'Esta área es para el equipo de Pet Seen.', deniedBody: 'Inicia sesión con una cuenta autorizada para revisar los reportes de contenido.', loading: 'Cargando reportes…', error: 'No pudimos cargar la cola de moderación. Inténtalo de nuevo.', emptyTitle: 'No hay reportes por revisar.', emptyBody: 'Los nuevos reportes de las páginas públicas aparecerán aquí.', unavailableCase: 'Caso no disponible', viewCase: 'Ver caso público', statusLabel: 'Estado del reporte', status: { open: 'Abierto', reviewed: 'Revisado', dismissed: 'Descartado', actioned: 'Con acción' } },
      dashboard: {
        eyebrow: 'Tus casos', title: 'Administra tus casos de mascotas perdidas.', intro: 'Mantén los detalles actualizados y cierra el caso cuando ya no necesite compartirse.', newCase: 'Iniciar un caso nuevo', loading: 'Cargando tus casos…', loadError: 'No pudimos cargar tus casos. Inténtalo de nuevo.', signInTitle: 'Inicia sesión para administrar tus casos.', signInBody: 'Tus casos están vinculados a tu cuenta para que solo tú puedas actualizarlos.', emptyTitle: 'Aún no tienes casos de mascotas perdidas.', emptyBody: 'Inicia un caso cuando necesites ayuda de personas cerca.', viewPublic: 'Ver página pública', pet: 'Mascota', caseTitle: 'Título del caso', petName: 'Nombre de la mascota', breed: 'Raza', colour: 'Color o marcas', description: 'Detalles útiles', lastSeenPlace: 'Lugar o punto de referencia de la última vez visto', lastSeenTime: 'Hora de la última vez visto', locationNote: 'Las ubicaciones exactas nunca se muestran públicamente.', saveChanges: 'Guardar cambios', saving: 'Guardando…', saved: 'Tus cambios se guardaron.', saveError: 'No pudimos guardar esos cambios. Inténtalo de nuevo.', statusError: 'No pudimos actualizar este caso. Inténtalo de nuevo.', statusSaved: 'El estado del caso se actualizó.', edit: 'Editar detalles', changeStatus: 'Estado del caso', reunitedNote: 'Marcado como reunido. Este caso ya no es público.', closedNote: 'Este caso está cerrado y ya no es público.', cancel: 'Cancelar', sightings: 'Reportes de avistamientos', sightingTimeline: 'Ubicaciones exactas de los avistamientos', sightingPrivacy: 'Estas ubicaciones son privadas para ti y el equipo de Pet Seen.', coordinates: 'Ubicación exacta en el mapa', status: { draft: 'Borrador', published: 'Aún perdida — público', closed: 'Cerrado — no público', reunited: 'Reunido — no público', removed: 'Eliminado', expired: 'Vencido' },
      },
      sighting: {
        progress: 'Reportar un avistamiento', eyebrow: 'No necesitas una cuenta', title: 'Cuéntanos qué viste.', intro: 'Un reporte claro le da a la persona dueña información útil sin mostrar públicamente tus datos de contacto.', petQuestion: '¿Sabes qué mascota podría ser?', petOrCase: 'Mascota o caso', knownPet: 'Milo — zona de Victoria Park', unknownPet: 'No estoy seguro/a / es otra mascota', petHelp: 'Puedes enviar un avistamiento aunque no sepas qué mascota es.', whenWhere: '¿Dónde y cuándo?', where: '¿Dónde viste a la mascota?', whereHint: 'Calle, parque o punto de referencia', when: '¿Cuándo la viste?', whenHint: 'Por ejemplo, hoy a las 5:15 p. m.', detailsQuestion: '¿Qué notaste?', details: 'Detalles', detailsHint: 'Color, collar, dirección en la que iba o cualquier otro dato que pueda ayudar.', addPhoto: 'Agrega una foto', photoHint: 'Es opcional, pero ayuda si puedes tomarla sin riesgo.', privacy: 'Tu ubicación exacta se comparte solo con la persona dueña del caso vinculado y las personas administradoras de Pet Seen.', locationHelp: 'Usa tu ubicación actual, mueve el pin o ingresa las coordenadas manualmente.', useLocation: 'Usar mi ubicación', pinNote: 'Mueve el pin o toca el mapa para confirmar el lugar exacto donde viste a la mascota.', latitude: 'Latitud', longitude: 'Longitud', locationUnavailable: 'Tu navegador no puede proporcionar una ubicación. Mueve el pin o ingresa las coordenadas manualmente.', locationDenied: 'No pudimos acceder a tu ubicación. Permite el acceso y vuelve a intentarlo, o mueve el pin o ingresa las coordenadas manualmente.', invalidLocation: 'Ingresa una latitud y longitud válidas.', unavailable: 'Los reportes de avistamientos no están disponibles en este entorno.', submitting: 'Enviando…', thanksTitle: 'Avistamiento compartido.', thanksBody: 'Gracias. Si vinculaste un caso, su persona dueña ya puede ver el lugar y hora exactos que reportaste.',
      },
      auth: {
        eyebrow: 'Acceso a la cuenta', title: 'Inicia sesión con tu correo electrónico.', accountTitle: 'Tu cuenta', intro: 'Te enviaremos un enlace seguro. No necesitas contraseña.', emailLabel: 'Correo electrónico', emailHint: 'tu@ejemplo.com', sendLink: 'Enviarme un enlace para iniciar sesión', sentTitle: 'Revisa tu correo electrónico.', sentBody: 'Enviamos un enlace seguro a {{email}}.', toast: 'Has iniciado sesión.', privacy: 'Usamos tu correo electrónico solo para proteger tu cuenta y contactarte sobre tus casos.', setupNote: 'La autenticación necesita ajustes del entorno local antes de que puedas enviar un enlace.', notConfigured: 'La autenticación no está configurada en este entorno.', loading: 'Revisando tu estado de inicio de sesión…', signedInTitle: 'Has iniciado sesión.', signedInBody: 'Tu cuenta usa {{email}}.', signOut: 'Cerrar sesión',
      },
      placeholders: {
        laterRelease: 'Próxima versión', foundTitle: 'Los reportes de mascotas encontradas llegarán pronto.', foundBody: 'Por ahora, usa un reporte de avistamiento para compartir dónde viste a una mascota.', accountAccess: 'Acceso a la cuenta', authTitle: 'El inicio de sesión usará un enlace seguro por correo electrónico.', authBody: 'No necesitarás una contraseña. Estamos creando esta función junto con el flujo de mascotas perdidas.', notFound: 'No encontrado', notFoundTitle: 'Esta página todavía no existe.',
      },
      footer: 'Ayudamos a que las mascotas vuelvan a casa, juntos.',
    },
  },
} as const

export type AppLocale = keyof typeof resources
