-- PS-106: Public case identifiers are generated by the database, rather than
-- being derived from a pet or case ID. 16 random bytes gives each URL 128 bits
-- of entropy while the hexadecimal form remains URL-safe and case-insensitive.

create or replace function public.generate_public_case_slug()
returns text
language sql
volatile
set search_path = pg_catalog, extensions
as $$
  select encode(extensions.gen_random_bytes(16), 'hex');
$$;

alter table public.missing_cases
  alter column public_slug set default public.generate_public_case_slug();

create or replace function public.assign_missing_case_public_slug()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    -- Ignore client-provided values so public URLs cannot be selected or
    -- inferred by callers.
    new.public_slug = public.generate_public_case_slug();
  elsif new.public_slug is distinct from old.public_slug then
    raise exception 'A missing case public URL cannot be changed';
  end if;

  return new;
end;
$$;

create trigger missing_cases_assign_public_slug
  before insert or update of public_slug on public.missing_cases
  for each row execute procedure public.assign_missing_case_public_slug();

revoke all on function public.generate_public_case_slug() from public;
revoke all on function public.assign_missing_case_public_slug() from public;
grant execute on function public.generate_public_case_slug() to authenticated;
